### ISSUE TITLE
Components should accept theme overrides

### ISSUE THREAD

**Issue by AlanBreck** [brave/leo#22]
If the user's preference is dark mode, but the component, or an ancestor contains `data-theme="light"`, the component should use light mode.

The following CSS successfully allows `[data-theme]` overrides:
Codepen: https://codepen.io/petemill/pen/poVzRxv
```css
.component {
  color: var(--text-color);

  --text-color: black;
  [data-theme="dark"] &,
  &[data-theme="dark"] {
    --text-color: white;
  }
  @media (prefers-color-scheme: dark) {
    &:not([data-theme="light"] &):not(&[data-theme="light"]) {
      --text-color: white;
    }
  }
}
```

The problem with this is that it's tedious to write. We'd like to create a PostCSS plugin to transform the following into the above:

```css
.component {
  color: var(--text-color);
  --text-color: black;

  @darkmode {
    --text-color: white;
  }
}
```

**Comment by AlanBreck** [comment]
I tried something like this, but that selector won't work as intended. Must be that `:not` has to have a specific element.

```@media (prefers-color-scheme: dark) {
      :global(:not([data-theme='light'])) &,
      &:not(.light) {
        --bg: var(--color-primary-dark-mode-50);
        --bg-hover: var(--color-primary-dark-mode-60);
        --bg-active: var(--color-primary-dark-mode-30);
        --bg-focus: var(--color-primary-dark-mode-50);
        --bg-loading: var(--color-primary-dark-mode-60);
      }
    }```

**Comment by fallaciousreasoning** [comment]
Okay, so I've got this working (#25). Does this seem sensible output wise:

Input
```sass
.leoButton.isSecondary {
    @darkmode {
      --bg: black;
      --color-hover: var(--color-secondary-dark-mode-80);
    }
  }
```

Output
```css
@media(prefers-color-scheme: dark) {
    .leoButton.isSecondary:not([data-theme=light] .leoButton.isSecondary):not([data-theme=light]) {
        --bg: black;
        --color-hover: var(--color-secondary-dark-mode-80)
    }
}

.leoButton.isSecondary[data-theme=dark] , [data-theme=dark] .leoButton.isSecondary {
    --bg: black;
    --color-hover: var(--color-secondary-dark-mode-80)
}
```

There's a playground here (only supports CSS though, sorry): https://astexplorer.net/#/gist/96fe6372b3f091e7faa53cf58fda54af/da4d0c63f42bc85cb706359ccad2bc9517ff364f

**Comment by AlanBreck** [comment]
@fallaciousreasoning, this is crazy, crazy awesome! Only little nit would be if we could place the media query at the bottom of that output.

**Comment by fallaciousreasoning** [comment]
Sure can! I also had a concern about how this is going to work with WebComponents - I think with the shadow DOM the `[data-theme=dark]  .my-component` selector isn't going to work (because the selector will only consider elements in the same shadow DOM)

**Comment by fallaciousreasoning** [comment]
I think we can maybe use `host-context([data-theme=dark]) .my-component` but I'm pretty sure it will only penetrate up one layer in the shadow DOM.

**Comment by fallaciousreasoning** [comment]
Okay, so turns out it will punch up through multiple shadow DOMs. I have a wee demo here
https://accessible-goldenrod-sidecar.glitch.me/ ([source](https://glitch.com/edit/#!/accessible-goldenrod-sidecar)). Things mostly seem to work. 

The only problem I can see is that the CSS selector doesn't respect closest `[data-theme]` selector. For example:

```html

<body data-theme='dark'>
	<my-component data-theme='light'> <!-- This will be dark -->
	</my-component>
</body>
```

**Comment by AlanBreck** [comment]
Not spam! This is really awesome stuff.

> The only problem I can see is that the CSS selector doesn't respect closest `[data-theme]`. For example:

Is the above unique to web components?

**Comment by fallaciousreasoning** [comment]
I don't think the above is - I think that's just a property of how the selectors work (but I could be wrong, my CSS is not too swish)

**Comment by AlanBreck** [comment]
I may have over simplified, but I think it should work. https://codepen.io/AlanBreck/pen/OJZJyRQ

**Comment by AlanBreck** [comment]
We could wrap the default rules like this:

```css
:root,
[data-theme="light"] {
	--bg: white;
	--textColor: black;
}
```

Codepen: https://codepen.io/AlanBreck/pen/OJZJyRQ

**Comment by fallaciousreasoning** [comment]
That's cool! It'll definitely work for the default rules but I'm not sure how we can apply it in a generic way though. We need to switch which set of styles the component uses based on the theme. I don't think we can get away with just setting CSS variables.

For example, how would we support this component?
```css
.component {
	display: flex;
	flex-direction: 'row';

	@darkmode {
		flex-direction: 'column';
	}
}
```

**Comment by AlanBreck** [comment]
Same way. The example above isn't dependent upon containing CSS variables:

```div {
	padding: 12px;
}

:root,
[data-theme="light"] {
	color: black;
	background: white;
}

[data-theme="dark"] {
	color: white;
	background: black;
}```

I updated the Codepen to demonstrate: https://codepen.io/AlanBreck/pen/OJZJyRQ

**Comment by AlanBreck** [comment]
Ok. Gnarlier and gnarlier, but here it is:

```css
.component,
.component[data-theme="light"] {
	display: flex;
	flex-direction: row;
	background: pink;
	padding: 12px;
}

.component[data-theme="dark"],
[data-theme="dark"] .component:not([data-theme="light"]) {
	flex-direction: column;
	background: red;
}

@media (prefers-color-scheme: dark) {
	.component:not([data-theme="light"] .component):not([data-theme="light"]) {
		flex-direction: column;
		background: red;
	}
}
```

Codepen: https://codepen.io/AlanBreck/pen/JjvjYVN

**Comment by fallaciousreasoning** [comment]
I think that means we'd only be able to change the theme on the component though. I think this breaks:

```html
<div data-theme="dark" class="component"> <!-- Dark -->
	  <div data-theme="light"> <!-- Takes light CSS variables because of :root, [data-theme="light"] {} -->
		  <div class="component"> <!-- Has dark styles for .component, has light CSS variables -->
			  <span>One</span>
			  <span>Two</span>
			  <span>Three</span>
			  <span>Four</span>
		  </div>
	  </div>
</div>
```

Codepen: https://codepen.io/fallaciousreasoning/pen/jOxOWWE

I'm kind of wondering if this is a bit of a hole we're getting ourselves into. Maybe we should be doing this in JS?

```ts
const getThemeOverride = (el: HTMLElement) => {
	while (el) {
		const theme = el.dataset['theme'];
		if (theme) return theme;

		el = el.parent;
	}
}
```

Although this opens a whole new can of worms wrt updating when a parent data-theme gets changed :laughing:

**Comment by AlanBreck** [comment]
Ok... this is getting pretty crazy, but...

```css
.component,
[data-theme="light"] .component {
	display: flex;
	flex-direction: row;
	background: pink;
	padding: 12px;
}

.component[data-theme="dark"],
[data-theme="dark"] :not([data-theme="light"]) .component:not([data-theme="light"]) {
	flex-direction: column;
	background: red;
}

@media (prefers-color-scheme: dark) {
	.component:not([data-theme="light"] .component):not([data-theme="light"]) {
		flex-direction: column;
		background: red;
	}
}
```

Codepen: https://codepen.io/AlanBreck/pen/JjvjYVN

**Comment by fallaciousreasoning** [comment]
You're a wizard :laughing: I'll have a play, and see how it feels.

Maybe we could deliberately limit whereabouts you can put one of these attributes (i.e. only on our custom components). That way we might be able to just ignore a bunch of these edge cases.

**Comment by fallaciousreasoning** [comment]
Okay, I did manage to break it with an div wrapper with no `data-theme` attribute but I don't really know how :laughing:.

```html
<div class="component" data-theme="dark">
	<span>One</span>
	<span>Two</span>
	<span>Three</span>
	<span>Four</span>
	
	<div>
		<div data-theme="light">
			<div class="component"> <!-- For some reason this is dark. If I remove the empty div wrapper it's fine.  -->
				<span>One</span>
				<span>Two</span>
				<span>Three</span>
				<span>Four</span>
			</div>
		</div>
	</div>
</div>
```

I think designing the perfect selector is going to be a pretty thankless task, and I'm not sure how often we're going to need madness like this. I reckon there are a couple of approaches we could go for here (I think agree JS is a bad idea).
1. We only care about this attribute if it's on the body: `body[data-theme=dark] { /* dark styles */ }`
    I like this option because it's by far the simplest. I don't know how often we'd want to change the styles for a specific component, but it seems like something we could solve when we encounter it.
2. We add a toggle to each of our components for setting dark mode. This is probably a bit more work to set up but I'm pretty confident I could do some trickery to get it injecting into each component automatically.
3. We create some kind of `<ThemeContext mode='dark'>` component, and work out how to wire it up. I think this is pretty doable, but it would be a JS solution. That said, we're also talking about `WebComponents` here, so users are going to need JS enabled any way, or nothing will work.

**Comment by AlanBreck** [comment]
We definitely need the overrides for specific elements, and not just the body. I've encountered several scenarios for this, a site footer being a prime example.

Additionally, since Leo will be consumed by plain old HTML apps (like brave.com), the solution can't be component or JS based since the styles get extracted into CSS chunks which are used as Tawilwind plugins.

I'd propose that we set a reasonable limit to how much nesting can take place, and develop the right selector to account for those uses, and then document how it could fail in others.

**Comment by AlanBreck** [comment]
My earlier attempts erred from the truth of @petemill's original selector:

```css
&:not([data-theme="light"] &):not(&[data-theme="light"])
```

This might solve all the cases?

```css
.component {
	display: flex;
	flex-direction: row;
	background: pink;
	padding: 12px;
}

.component[data-theme="dark"]:not([data-theme="light"] .component):not([data-theme="light"]) {
	flex-direction: column;
	background: red;
}

@media (prefers-color-scheme: dark) {
	.component:not([data-theme="light"] .component):not([data-theme="light"]) {
		flex-direction: column;
		background: red;
	}
}
```

Codepen: https://codepen.io/AlanBreck/pen/JjvjYVN

**Comment by petemill** [comment]
That example works well, but I think we need to add a custom element in to the mix so we can see what we need to do to break out of shadow DOM. All the react uses of the svelte components will be rendered via shadow DOM, and possible regular svelte too, depending on how the element is created.

**Comment by petemill** [comment]
Also, if we want to remove any complexity then I'd suggest we prefer removing the ability for a specific component to have data-theme applied directly to it, since it can always be wrapped in a `<div data-theme="dark">`. But perhaps let's try to keep everything in there unless it's just too much to solve in 1 go.

**Comment by fallaciousreasoning** [comment]
I've had a play with the Shadow DOM stuff, and I'm pretty sure we'll be able to tweak whatever solution we come up with to work with it via `:host-context`.

The above example breaks with this CodePen: https://codepen.io/fallaciousreasoning/pen/jOxEmRY

My main concern is that this is going to break encapsulation - now, by changing properties somewhere way up the DOM we can accidentally break overrides somewhere else.

```html
<div style="margin-top: 12px;" class="component" data-theme="dark"> <!-- Is dark. This is good -->
	<span>Should</span>
	<span>be</span>
	<span>dark</span>
	
	<div>
		<div data-theme="light">
			<div class="component" data-theme="dark"> <!-- Is rendered light, which is pretty confusing. It's pretty hard to build a mental model as to why. -->
				<span>Should</span>
				<span>be</span>
				<span>dark</span>
			</div>
		</div>
	</div>
</div>
</div>
```

(I think this selector is breaking it `.component[data-theme="dark"]:not([data-theme="light"] .component) `, changing it to `.component[data-theme=dark]` seems to fix it but I'm sure it breaks something else).

I've been playing around with this a bit more and I have a couple of insights:

1. `.component[data-theme=dark]` should always set dark mode. It's the simplest case.
2. If any parent element has a [data-theme] attribute, we should ignore `prefers-color-scheme` (in this case styles will be handled by our `[data-theme=dark]` selector).

This gives us:

```css

.component {
	/** Light Styles **/
}

.component[data-theme=dark] {
	/** Dark Styles **/
}

@media (prefers-color-scheme: dark) {
	.component:not([data-theme]) {
		/** Dark Styles **/
	}
}

```

which supports toggling darkmode on a specific component, but not on it's children. Maybe we can generate selectors for certain levels of nesting?

```css

@darkmode (depth: 3) {
	/** Dark Styles **/ 
}

/** would generate: **/

/* Three levels of style switches */
[data-theme=dark] [data-theme=light] [data-theme=dark] .component:not([data-theme=dark] [data-theme=light] [data-theme=dark] [data-theme=light] .component):not([data-theme=light]),
/* Two levels of style switches */
[data-theme=light] [data-theme=dark] .component:not([data-theme=light] [data-theme=dark] [data-theme=light] .component):not(data-theme=light),
/* One level of style switches */
[data-theme=dark] .component:not([data-theme=dark] [data-theme=light] .component):not(data-theme=light) 
 {
	/** Dark Styles **/
}

```

**Comment by fallaciousreasoning** [comment]
I've update the plugin to generate levels of nesting support, and I'm using it to generate the custom styles for a new :
https://astexplorer.net/#/gist/96fe6372b3f091e7faa53cf58fda54af/1be405b6578cf30b288f4aafcb537007c082c2c4

The pen, updated with the generated CSS for 3 levels of nesting.
https://codepen.io/fallaciousreasoning/pen/XWqJgxW

**Comment by fallaciousreasoning** [comment]
Okay, I've dug a big more and I've found a few problems:
1) Firefox & Safari don't support the `:host-context` selector. This means we can't have a CSS selector on those browsers which can query if a parent element has a `[data-theme]` attribute. For webcomponents, we're going to need to use JS, I'm afraid.
2) Chromium browsers don't support `combinators` inside `:host-context()`. This means `:host-context([data-theme=dark])` is valid but `:host-context(div [data-theme=dark])` and `:host-context([data-theme=dark] [data-theme=light])` are not, which pretty completely breaks my above approach.

**Comment by petemill** [comment]
> For webcomponents, we're going to need to use JS, I'm afraid.
WebComponent, by definition will be using JS, so I think a JS solution could be ok for those

> Chromium browsers don't support combinators inside :host-context(). This means :host-context([data-theme=dark]) is valid but :host-context(div [data-theme=dark]) and :host-context([data-theme=dark] [data-theme=light]) are not,
Then I guess maybe a JS approach investigation is needed, it would also solve this.

So I think we're all feeling the need to simplify this, and maybe that is that the consumer just needs to specify the theme as an attribute (or class name) for every component. This does however get tricky when a component has child elements.

However, if we're sticking with the complicated approach to solve all the goals, another layer of complexity could be for svelte to detect if it's a WebComponent, and use a JS approach, and otherwise provide a css-compatible method when it's rendered regularly (i.e. not shadow DOM)

**Comment by fallaciousreasoning** [comment]
@AlanBreck & I came up with an even crazier solution, which I think solves all our problems (even with WebComponents!):

```css
.component {
	padding: 12px;
	background: pink;
	
	display: flex;
	flex-direction: row;
}

@darkmode {
	.component {
		background: red;
		flex-direction: column;
	}
}
```

is transformed to:

```css
:root, [data-theme=light] {
	--\.component_background: pink;
	--\.component_flex-direction: row;
}

[data-theme=dark] {
	--\.component_background: red;
	--\.component_flex-direction: column;
}

.component {
	padding: 12px;
	background: var(--\.component_background);

	display: flex;
	flex-direction: var(--\.component_flex-direction);
}
```

I've put together a basic AST explorer for it and it seems to work :fearful: 
https://astexplorer.net/#/gist/11c149ab5b4ece2148e3963e7b3f1813/5fbcd1ae1da261260eeb6cc8a5b5c220607c8cbd
And here's a pen using the generated styles:
https://codepen.io/fallaciousreasoning/pen/xxjZZrb

I'm going to tidy up the generator a bit to work with `,` selectors but I think this is our way forwards :smile:
